# Generated by Django 2.2.4 on 2020-01-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('oily', models.IntegerField(default=0)),
                ('dry', models.IntegerField(default=0)),
                ('sensitive', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
