# Generated by Django 2.2.4 on 2020-01-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField(default=0, help_text='KRW')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], default='all', max_length=10)),
                ('monthly_sales', models.IntegerField(default=0, help_text='이번 달 판매 수량')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.Category')),
                ('ingredients', models.ManyToManyField(related_name='products', to='ingredients.Ingredient')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
